version: 2
updates:
  # uvパッケージの更新設定
  - package-ecosystem: "uv"
    directory: "/src/api"
    open-pull-requests-limit: 2
    schedule:
      interval: weekly
    labels:
      - "dependencies"
      - "uv"
    groups:
      api-version:
        applies-to: version-updates
        patterns:
          - "*"
      api-security:
        applies-to: security-updates
        patterns:
          - "*"
    commit-message:
      prefix: "deps(api)"
      prefix-development: "deps(api)"
  # npmパッケージの更新設定
  - package-ecosystem: "npm"
    directory: "/src/web"
    open-pull-requests-limit: 2
    schedule:
      interval: weekly
    labels:
      - "dependencies"
      - "npm"
    groups:
      web-version:
        applies-to: version-updates
        patterns:
          - "*"
      web-security:
        applies-to: security-updates
        patterns:
          - "*"
    commit-message:
      prefix: "deps(web)"
      prefix-development: "deps(web)"
  # GitHub Actionsの更新設定
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      github-actions-version:
        applies-to: version-updates
        patterns:
          - "*"
      github-actions-security:
        applies-to: security-updates
        patterns:
          - "*"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "deps(github-actions)"
      prefix-development: "deps(github-actions)"
