"""株式分割対応: stock_splitsテーブルとadjusted_quantityカラム追加

Revision ID: 0b8f7bee9310
Revises: 14594f93459a
Create Date: 2026-01-09 14:04:03.395530

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0b8f7bee9310"
down_revision: Union[str, None] = "14594f93459a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_splits",
        sa.Column("split_id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=15), nullable=False),
        sa.Column("split_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("split_ratio", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["symbol"],
            ["stocks.symbol"],
        ),
        sa.PrimaryKeyConstraint("split_id"),
        sa.UniqueConstraint("symbol", "split_date", name="uq_symbol_split_date"),
    )
    op.add_column(
        "transactions", sa.Column("adjusted_quantity", sa.Numeric(precision=10, scale=4), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "adjusted_quantity")
    op.drop_table("stock_splits")
    # ### end Alembic commands ###
