"""change quanntity Numeric 2 to 4

Revision ID: 14594f93459a
Revises: 84f69865ac6f
Create Date: 2025-04-08 15:53:51.227667

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "14594f93459a"
down_revision: str | None = "84f69865ac6f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dividend",
        "shares_owned",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.Numeric(precision=10, scale=4),
        existing_nullable=False,
    )
    op.alter_column(
        "holdings",
        "quantity",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.Numeric(precision=10, scale=4),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "holdings",
        "quantity",
        existing_type=sa.Numeric(precision=10, scale=4),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "dividend",
        "shares_owned",
        existing_type=sa.Numeric(precision=10, scale=4),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
