"""add realized_pl to transactions

Revision ID: 386b374db3c4
Revises: efe971be2748
Create Date: 2025-03-26 10:05:37.584558

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "386b374db3c4"
down_revision: str | None = "efe971be2748"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. まずNULL値を許可してカラムを追加
    op.add_column("transactions", sa.Column("realized_pl", sa.Numeric(precision=10, scale=2), nullable=True))

    # 2. 既存のレコードにデフォルト値を設定
    op.execute("UPDATE transactions SET realized_pl = 0.00 WHERE realized_pl IS NULL")

    # 3. NOT NULL制約を設定
    op.alter_column(
        "transactions", "realized_pl", existing_type=sa.Numeric(precision=10, scale=2), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "realized_pl")
    # ### end Alembic commands ###
