"""change quanntity of transaction NUmeric 2 to 4

Revision ID: 84f69865ac6f
Revises: 9a9b0e64c6f7
Create Date: 2025-04-08 15:43:06.517246

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "84f69865ac6f"
down_revision: str | None = "9a9b0e64c6f7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transactions",
        "quantity",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.Numeric(precision=10, scale=4),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transactions",
        "quantity",
        existing_type=sa.Numeric(precision=10, scale=4),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
