"""add is_admin to User

Revision ID: 9a9b0e64c6f7
Revises: e8b008a4407a
Create Date: 2025-04-04 08:49:03.264379

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a9b0e64c6f7"
down_revision: str | None = "e8b008a4407a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # uq_user_symbol制約が既に存在するので、この行を削除または無効化
    # op.create_unique_constraint('uq_user_symbol', 'holdings', ['user_id', 'symbol'])

    # is_adminカラムの追加だけ実行
    op.add_column("users", sa.Column("is_admin", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_admin")
    # op.drop_constraint('uq_user_symbol', 'holdings', type_='unique')
    # ### end Alembic commands ###
