"""update_symbol_length_to_15

Revision ID: a86e14099dc8
Revises: f470ae6f7e9e
Create Date: 2025-02-25 21:53:04.093620

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a86e14099dc8"
down_revision: str | None = "f470ae6f7e9e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dividend",
        "symbol",
        existing_type=sa.VARCHAR(length=10),
        type_=sa.String(length=15),
        existing_nullable=False,
    )
    op.alter_column(
        "holdings",
        "symbol",
        existing_type=sa.VARCHAR(length=10),
        type_=sa.String(length=15),
        existing_nullable=False,
    )
    op.alter_column(
        "stock_jpx_details",
        "symbol",
        existing_type=sa.VARCHAR(length=10),
        type_=sa.String(length=15),
        existing_nullable=False,
    )
    op.alter_column(
        "stock_us_details",
        "symbol",
        existing_type=sa.VARCHAR(length=10),
        type_=sa.String(length=15),
        existing_nullable=False,
    )
    op.alter_column(
        "stocks",
        "symbol",
        existing_type=sa.VARCHAR(length=10),
        type_=sa.String(length=15),
        existing_nullable=False,
    )
    op.alter_column(
        "transactions",
        "symbol",
        existing_type=sa.VARCHAR(length=10),
        type_=sa.String(length=15),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transactions",
        "symbol",
        existing_type=sa.String(length=15),
        type_=sa.VARCHAR(length=10),
        existing_nullable=False,
    )
    op.alter_column(
        "stocks",
        "symbol",
        existing_type=sa.String(length=15),
        type_=sa.VARCHAR(length=10),
        existing_nullable=False,
    )
    op.alter_column(
        "stock_us_details",
        "symbol",
        existing_type=sa.String(length=15),
        type_=sa.VARCHAR(length=10),
        existing_nullable=False,
    )
    op.alter_column(
        "stock_jpx_details",
        "symbol",
        existing_type=sa.String(length=15),
        type_=sa.VARCHAR(length=10),
        existing_nullable=False,
    )
    op.alter_column(
        "holdings",
        "symbol",
        existing_type=sa.String(length=15),
        type_=sa.VARCHAR(length=10),
        existing_nullable=False,
    )
    op.alter_column(
        "dividend",
        "symbol",
        existing_type=sa.String(length=15),
        type_=sa.VARCHAR(length=10),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
