"""Update market field to str

Revision ID: e69f37e6ae41
Revises: 5caf002508f1
Create Date: 2025-02-12 20:28:24.815942

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e69f37e6ae41"
down_revision: Union[str, None] = "5caf002508f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stocks") as batch_op:
        batch_op.alter_column("market", existing_type=sa.String(length=20), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stocks") as batch_op:
        batch_op.alter_column("market", existing_type=sa.String(length=20), nullable=False)
    # ### end Alembic commands ###
