"""Add line_user_id to users table

Revision ID: e8b008a4407a
Revises: 386b374db3c4
Create Date: 2025-04-01 21:11:35.915696

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e8b008a4407a"
down_revision: Union[str, None] = "386b374db3c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # uq_user_symbol制約はすでにmodels.pyで定義され存在するため削除
    op.add_column("users", sa.Column("line_user_id", sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, "users", ["line_user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "line_user_id")
    # uq_user_symbol制約はmodels.pyで定義されているため、ここでは削除しない
    # ### end Alembic commands ###
