"""add total_pl and total_pl_percentage columns

Revision ID: e9bc1da32174
Revises: a1b2c3d4e5f6
Create Date: 2026-01-30 13:25:27.565716

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e9bc1da32174"
down_revision: str | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("holdings", sa.Column("total_pl", sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column(
        "holdings", sa.Column("total_pl_percentage", sa.Numeric(precision=5, scale=2), nullable=True)
    )
    op.add_column(
        "portfolio_history",
        sa.Column("total_pl", sa.Numeric(precision=10, scale=2), nullable=False, server_default="0"),
    )
    op.add_column(
        "portfolio_history",
        sa.Column(
            "total_pl_percentage", sa.Numeric(precision=5, scale=2), nullable=False, server_default="0"
        ),
    )
    op.alter_column("stock_splits", "user_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("stock_splits", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_column("portfolio_history", "total_pl_percentage")
    op.drop_column("portfolio_history", "total_pl")
    op.drop_column("holdings", "total_pl_percentage")
    op.drop_column("holdings", "total_pl")
    # ### end Alembic commands ###
