"""initial migration

Revision ID: f470ae6f7e9e
Revises: 
Create Date: 2025-02-22 21:22:54.116879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f470ae6f7e9e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=True),
    sa.Column('market', sa.String(length=20), nullable=False),
    sa.Column('security_type', sa.Enum('STOCK', 'ETF', 'REIT', 'FUND', name='security_types'), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('dividend',
    sa.Column('dividend_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('shares_owned', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['stocks.symbol'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('dividend_id')
    )
    op.create_table('holdings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('average_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('market_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('realized_pl', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_dividend', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unrealized_pl', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unrealized_pl_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['stocks.symbol'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'symbol'),
    sa.UniqueConstraint('user_id', 'symbol', name='uq_user_symbol')
    )
    op.create_table('portfolio_history',
    sa.Column('history_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_market_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_unrealized_pl', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_unrealized_pl_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total_realized_pl', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_dividend', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('history_id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_user_date_portfolio')
    )
    op.create_table('stock_jpx_details',
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('sector_17_code', sa.String(length=2), nullable=True),
    sa.Column('sector_17_name', sa.String(length=50), nullable=True),
    sa.Column('sector_33_code', sa.String(length=4), nullable=True),
    sa.Column('sector_33_name', sa.String(length=50), nullable=True),
    sa.Column('market_segment', sa.String(length=20), nullable=False),
    sa.Column('market_code', sa.String(length=20), nullable=True),
    sa.Column('market_name', sa.String(length=50), nullable=True),
    sa.Column('margin_trading', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['stocks.symbol'], ),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('stock_us_details',
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('gics_sector', sa.String(length=50), nullable=True),
    sa.Column('gics_industry', sa.String(length=50), nullable=True),
    sa.Column('sp500_component', sa.Boolean(), nullable=True),
    sa.Column('market', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['stocks.symbol'], ),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('transactions',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('transaction_type', sa.Enum('buy', 'sell', name='transaction_types'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('usd_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('adjusted_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_type', sa.Enum('ジュニアNISA', '旧NISA', 'NISA(つみたて投資枠)', 'NISA(成長投資枠)', name='account_types'), nullable=False),
    sa.Column('fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['stocks.symbol'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('stock_us_details')
    op.drop_table('stock_jpx_details')
    op.drop_table('portfolio_history')
    op.drop_table('holdings')
    op.drop_table('dividend')
    op.drop_table('users')
    op.drop_table('stocks')
    # ### end Alembic commands ###
