[project]
name = "api"
version = "0.1.0"
description = "Investment Management API"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.100.0",
    "sqlalchemy>=2.0.0",
    "uvicorn>=0.22.0",
    "python-jose[cryptography]>=3.3.0",
    "passlib[bcrypt]>=1.7.4",
    "pydantic>=2.0.0",
    "python-multipart>=0.0.6",
    "alembic>=1.11.0",
    "asyncpg>=0.28.0",
    "pytz>=2025.1",
    "aiosqlite>=0.21.0",
    "python-dotenv>=1.0.1",
    "pydantic-settings>=2.7.1",
    "jquants-api-client>=1.7.3",
    "aiohttp>=3.11.12",
    "pytest>=8.3.4",
    "httpx>=0.28.1",
    "beautifulsoup4>=4.13.3",
    "pandas-datareader>=0.10.0",
    "pandas>=2.2.3",
    "pytest-mock>=3.14.0",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "pytest-asyncio>=0.25.3",
    "ruff>=0.9.5",
]

[tool.ruff]
# Allow lines to be as long as 120.
line-length = 127

[tool.setuptools]
packages = ["stock", "alembic"]
