services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: investlogix-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hogehoge
      POSTGRES_DB: investlogix
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: investlogix-api
    env_file:
      - ./api/.env
    environment:
      DB_HOST: db
    volumes:
      - ./api:/src
      - ./api/.dockervenv:/src/.venv
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    working_dir: /src

  web:
    image: node:22-alpine
    container_name: investlogix-web
    environment:
      VITE_API_URL: http://localhost:8000
    volumes:
      - ./web:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - api
    working_dir: /app
    command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm dev --host"